### PR TITLE
Fix issue #22

### PR DESCRIPTION
**Pull request by matbech**
Remove the subject header otherwise it will be duplicated.

### CODE REVIEW

**Comment by mwillbanks** [comment]
@matbech can you please add tests for this?

**Comment by matbech** [comment]
The Subject header is added by the php mail function on Windows. If an extra Subject header is present in the header array the result is a message with two Subject headers.

The request for an automated test is not reasonable because: 
1. There is already enough evidence of the bug:
- Manual test (reason for this PR)
- php source where the "Subject" header is added:
https://github.com/php/php-src/blob/0437aa2abf1eb494e4555d7d4dfbdbf566a59bdc/win32/sendmail.c#L595
https://github.com/php/php-src/blob/0437aa2abf1eb494e4555d7d4dfbdbf566a59bdc/win32/sendmail.c#L702

2. Writing an STMP server to intercept the mail communication from Window's php:mail is unreasonable, considering the evidence already presented.

**Comment by glensc** [comment]
@matbech can you just make test that if OS is windows the header is removed? not sure if the isWindows result can be mocked.

**Comment by matbech** [comment]
I'm sorry but I have a hard time to understand your sentence. This has been tested on Windows with PHP 7. There is no good reason to leave this bug open for more than 6 months now.

**Comment by glensc** [comment]
Did you test all other supported versions too?, PHP < 7

I'm trying to help, i don't care for one bit for windows support personally!

**Comment by weierophinney** [comment]
We've asked for tests, and blocked this for lack of tests; it's not a question of whether or not we want the fix, but wanting to ensure it *stays fixed*.

You can test this by mocking the result of what `isWindowsOs()` returns (potentially by extending the transport to hardcode the value), and checking the message generated to see if the header was removed.

If/when you are able to do that, please open a new pull request; until then, I'm closing this for now.

**Pull request closed without merging**
