### PR TITLE
fix header encode run into iconv Unknown error (7)

### LINKED ISSUE #33: \Zend\Mail\Storage\Imap Header value must be composed of printable US-ASCII characters and valid folding sequences.
I have an other issue : 
```php
        $mail = new \Zend\Mail\Storage\Imap(array('host' => 'myhost',
            'user' => 'mylogin',
            'password' => 'mypassword'));
$mail->getMessage(194)
```
From debug : 
```php
( ! ) Notice: iconv_mime_encode(): Unknown error (7) in .../vendor/zendframework/zend-mail/src/Header/HeaderWrap.php on line 119
Call Stack
#	Time	Memory	Function	Location
1	0.0025	241792	{main}( )	.../index.php:0
2	0.4338	5131376	Zend\Mvc\Application->run( )	.../index.php:17
3	0.6873	5857424	Zend\EventManager\EventManager->trigger( )	.../Application.php:314
4	0.6873	5857472	Zend\EventManager\EventManager->triggerListeners( )	.../EventManager.php:205
5	0.6886	5865392	call_user_func:{/.../vendor/zendframework/zend-eventmanager/src/EventManager.php:444} ( )	.../EventManager.php:444
6	0.6886	5865888	Zend\Mvc\DispatchListener->onDispatch( )	.../EventManager.php:444
7	0.6921	5911392	Zend\Mvc\Controller\AbstractController->dispatch( )	.../DispatchListener.php:93
8	0.6922	5911856	Zend\EventManager\EventManager->trigger( )	.../AbstractController.php:118
9	0.6922	5911904	Zend\EventManager\EventManager->triggerListeners( )	.../EventManager.php:205
10	0.6939	5927832	call_user_fun:{.../vendor/zendframework/zend-eventmanager/src/EventManager.php:444} ( )	.../EventManager.php:444
11	0.6939	5927960	Zend\Mvc\Controller\AbstractActionController->onDispatch( )	.../EventManager.php:444
12	0.6940	5928152	...\IndexController->indexAction( )	.../AbstractActionController.php:82
13	1.2227	5997920	Zend\Mail\Storage\Imap->getMessage( )	.../IndexController.php:58
14	1.2503	6042432	Zend\Mail\Storage\Message->__construct( )	.../Imap.php:118
15	1.2503	6042944	Zend\Mail\Storage\Part->__construct( )	.../Message.php:54
16	1.2512	6047184	Zend\Mime\Decode::splitMessage( )	.../Part.php:106
17	1.2542	6132128	Zend\Mail\Headers::fromString( )	.../Decode.php:141
18	1.2852	6191952	Zend\Mail\Headers->addHeaderLine( )	.../Headers.php:95
19	1.2852	6192000	Zend\Mail\Header\GenericHeader::fromString( )	.../Headers.php:231
20	1.2935	6193568	Zend\Mail\Header\GenericHeader->__construct( )	.../GenericHeader.php:37
21	1.2936	6193648	Zend\Mail\Header\GenericHeader->setFieldValue( )	.../GenericHeader.php:83
22	1.2936	6194856	Zend\Mail\Header\HeaderWrap::canBeEncoded( )	.../GenericHeader.php:129
23	1.2936	6195304	iconv_mime_encode ( )	.../HeaderWrap.php:119
```

From zf trace
```php
Message:
Header value must be composed of printable US-ASCII characters and valid folding sequences.
Pile d'exécution:
#0 .../vendor/zendframework/zend-mail/src/Header/GenericHeader.php(83): Zend\Mail\Header\GenericHeader->setFieldValue('ELIE Caroline <...')
#1 .../vendor/zendframework/zend-mail/src/Header/GenericHeader.php(37): Zend\Mail\Header\GenericHeader->__construct('To', 'ELIE Caroline <...')
#2 .../vendor/zendframework/zend-mail/src/Headers.php(231): Zend\Mail\Header\GenericHeader::fromString('To: ELIE Caroli...')
#3 .../vendor/zendframework/zend-mail/src/Headers.php(95): Zend\Mail\Headers->addHeaderLine('To: ELIE Caroli...')
#4 .../vendor/zendframework/zend-mime/src/Decode.php(141): Zend\Mail\Headers::fromString('MIME-Version: 1...', '\n')
#5 .../vendor/zendframework/zend-mail/src/Storage/Part.php(106): Zend\Mime\Decode::splitMessage('MIME-Version: 1...', 'MIME-Version: 1...', '')
#6 .../vendor/zendframework/zend-mail/src/Storage/Message.php(54): Zend\Mail\Storage\Part->__construct(Array)
#7 .../vendor/zendframework/zend-mail/src/Storage/Imap.php(118): Zend\Mail\Storage\Message->__construct(Array)
#8 .../module/Ent/src/Ent/Controller/IndexController.php(58): Zend\Mail\Storage\Imap->getMessage(194)
#9 .../vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Ent\Controller\IndexController->indexAction()
#10 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 .../vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 .../vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 .../vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 .../vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#15 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 .../vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 .../vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 .../vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 .../public/index.php(17): Zend\Mvc\Application->run()
#20 {main}
```

### PR DESCRIPTION
**Pull request by glensc**
proposed solution for #64, should also fix  #33
test included.

### CODE REVIEW

**Comment by glensc** [comment]
eh, the [changelog](https://github.com/zendframework/zend-mail/commit/e1b0ed650765f4c5be686d8dacc70ee991a7d19f) entry is slightly incorrect :)
the what the fix is based is written in this comment:
https://github.com/zendframework/zend-mail/issues/64#issuecomment-182122550

**Comment by glensc** [comment]
@weierophinney it got me curious how old the original fix was, so here it is (Dec 9, 2010):
https://github.com/eventum/eventum/commit/b09c8878425097ca97a16bbfdae799dae8d8f668

**Comment by glensc** [comment]
[that php.net bug](https://bugs.php.net/bug.php?id=53891) doesn't even contain any solution, so my suggestion is to drop it and just refer to ZF\Mail bugs #64 and #33 only

**Comment by smazurov** [comment]
@weierophinney any idea when 2.6.2 gets released?

**Comment by weierophinney** [comment]
Released it earlier today.

**Pull request merged**
