### PR TITLE
Complete #28

### PR DESCRIPTION
**Pull request by weierophinney**
This patch incorporates the patches from #28, with the following additions:

- Incorporates feedback regarding ASCII range.
- Removes an unnecessary test.
- Adds a test case in the `validateValues()` provider to ensure that `\r\n\t` is recognized as a valid header wrap.
- Updates the code so that this last test case actually passes.

In addition, I was unable to run php-cs-fixer when testing after running `composer update --prefer-lowest`. As such, this patch switches to phpcs, and corrects all CS issues flagged.

Fix #28 
Close #65

### CODE REVIEW

**Comment by Maks3w** [comment]
@weierophinney Note this should be backported to 2.4 series

**Comment by weierophinney** [comment]
@Maks3w why? I don't see any discussion around that on the original patch...

**Comment by Maks3w** [comment]
Because this bug was introduced by the zend mail headers security patch which it was applied to 2.4 too

**Comment by glensc** [comment]
hard to see what the changes here are, because phpcs diff in same MR. i attempted to cherry-pick this to 2.4 branch, but seems the changes are already there

40fbcbe08998605ca219ecbc7ac3b0c425aa768c
e1c049e759758f2a1a6875208a7f14923ee5292d

**Pull request merged**
