### PR TITLE
phpunit 6

### PR DESCRIPTION
**Pull request by kokspflanze**
drop php 5.5
added phpunit 6 support
travis update

i will do the `::class` job after that PR.

### CODE REVIEW

**Comment by Xerkus** [comment]
@kokspflanze please change branch to develop

**Comment by kokspflanze** [comment]
@Xerkus done

**Comment by kokspflanze** [comment]
@Xerkus ohh didnt saw them, these are skipped atm, so build say nothing=(

changed it=)

about the `Transport\NullTest` these is skipped because it doesnot work on php 7 (Cannot test Null transport under PHP 7; reserved keyword), so dont need to change it, also that namespace doesnt exist on phpunit 5.7.15, so if we change it we need for that the classname hack. i think that is not realy better as the the current solution.

**Comment by Xerkus** [comment]
grep, or its more modern alternative silversearcher, is your friend

**Comment by Xerkus** [comment]
@kokspflanze thank you

**Pull request merged**
